backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/settings/settings.md"
        label: "gdpr setting"
        name: "gdprSetting"
        fields:
          - { label: "GDPR text", name: "gdprText", widget: "text" }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          # - {label: Title, name: title, widget: string}
          # - {label: Image, name: image, widget: image}
          # - {label: Heading, name: heading, widget: string}
          - { label: Title, name: title, widget: string }
          - {
              label: Landing Page Text,
              name: landingPageText,
              widget: markdown,
            }
          - {
              label: "Grid Items",
              name: "gridItems",
              widget: "list",
              fields:
                [
                  {
                    label: Title,
                    name: title,
                    widget: string,
                    required: false,
                  },
                  { label: Link, name: link, widget: string, required: false },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/privacy/index.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "privacy-page",
            }
          - { label: Company Name, name: companyName, widget: string }
          - { label: Title, name: title, widget: string, required: true }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: string, required: true }
          - { label: Email Address, name: emailAddress, widget: string }
          - { label: Company Name, name: companyName, widget: string }
          - { label: Address Line 1, name: addressLine1, widget: string }
          - { label: Address Line 2, name: addressLine2, widget: string }
          - { label: Post Code, name: postCode, widget: string }
          - { label: Phone Number, name: phoneNumber, widget: string }
